### PR TITLE
New and better UI

### PR DESCRIPTION
**Pull request by SaptakBhoumik**
Sorry for being late actually I was busy with some of my other projects.
Changes I made:-
i)Improved the UI.
ii)Made the website responsive so it looks better on both mobile and cell phone
iii)Added icon in title tab
Things I couldn't do:- 
i)Sorry to say but I can't make the login page. I tried but failed
Suggestion:-
i)Add more content

Live demo- https://saptakbhoumik.github.io/teamlearn/teamlearn/public/index.html
Please check the demo site before merging. If you find any silly mistake or error let me know as soon as possible. I hope you will like it

### CODE REVIEW

**Comment by MrGithub2021** [comment]
What database r u using?

**Comment by SaptakBhoumik** [comment]
@MrGithub2021 I told you I can't make the log in page. I tried but failed sorry for that

**Comment by SaptakBhoumik** [comment]
I have improved the ui and made it responsive@MrGithub2021 @koreaneggroll

**Comment by SaptakBhoumik** [comment]
@MrGithub2021 any changes you want

**Comment by koreaneggroll** [comment]
oh damn this is a lot to review here. Ima get started soon and make sure everythin is ok. And a deep thanks from my heart for actually contributing to this project.

**Pull request merged**
