### PR TITLE
Create ruby.css and folders for Ruby

### PR DESCRIPTION
**Pull request by MrGithub2021**
We will make some folders for ruby.

### CODE REVIEW

**Comment by koreaneggroll** [comment]
looks good for now but if you could also make the html cuz i don't rly know what you're going for right now.

**Comment by MrGithub2021** [comment]
Ok, you can merge it.

**Comment by MrGithub2021** [comment]
BTW, I'm still wondering on how to make a C Editor.

**Comment by koreaneggroll** [comment]
u want to make an editor for the website ?

**Comment by MrGithub2021** [comment]
yea

**Comment by koreaneggroll** [comment]
oh i guess i could help on that later. so like tommorow. we'll see

**Comment by MrGithub2021** [comment]
I could mayb embed.

**Comment by MrGithub2021** [comment]
a compiler

**Comment by koreaneggroll** [comment]
if you know how to do that you're a god lol

**Comment by MrGithub2021** [comment]
About that database......... yea i found an example on [W3schools](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_password_val) and I can use SQlite

**Comment by koreaneggroll** [comment]
yeah i think we'll implement the database later on

**Comment by koreaneggroll** [comment]
and prob. gonna use psql

**Comment by MrGithub2021** [comment]
What psql?

**Comment by koreaneggroll** [comment]
postgreSQL

**Pull request merged**
