### PR TITLE
Update profile html to get a database

### PR DESCRIPTION
**Pull request by MrGithub2021**
Here we go!

### CODE REVIEW

**Comment by koreaneggroll** [comment]
wow you worked some time

**Comment by koreaneggroll** [comment]
lemme test it out and if it works ima squash and merge

**Comment by koreaneggroll** [comment]
whats up with creating the todos table ?

**Comment by koreaneggroll** [comment]
im pretty sure we don't make todos here :)

**Comment by MrGithub2021** [comment]
oop

**Comment by koreaneggroll** [comment]
and sign in button doesn't even work

**Comment by koreaneggroll** [comment]
still good job for making this

**Comment by MrGithub2021** [comment]
I just wanted to add an <a>

**Comment by MrGithub2021** [comment]
`<a>`

**Comment by MrGithub2021** [comment]
i did the changes

**Comment by koreaneggroll** [comment]
still one commit

**Comment by MrGithub2021** [comment]
actually, there are ```2```

**Comment by MrGithub2021** [comment]
demo [here](https://mrgithub2021.github.io/teamlearn/teamlearn/public/)

**Comment by koreaneggroll** [comment]
i still cant login. the button doesnt work

**Comment by MrGithub2021** [comment]
ok. Ima get help.

**Pull request closed without merging**
